[package]
name = "jsrunner"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jsrunner"
path = "src/server.rs"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
v8 = "0.95.0"

[build-dependencies]
tonic-build = "0.11"
